### ISSUE TITLE
toNano(1e-7) produces inadequate result

### ISSUE THREAD

**Issue by mcnckc** [toncenter/tonweb#58]
`toNano(1e-6)` works fine but
`toNano(1e-7).toNumber()` results in `2377000000000` on my machine.
It seems like it is exactly the reason why one can't send less than `1e-6` TON using the web wallet based on this library - https://ton.app/wallets/web-ton-wallet.
Correct me if I'm wrong, but by the standard one should be able to send less than `1000` nanoTON, despite it doesn't seem like a critical issue.
I know that the average fee is much greater.

**Comment by slavafomin** [comment]
We are on it, thank you for reporting this!

**Comment by slavafomin** [comment]
I've created an upstream issue: https://github.com/ethjs/ethjs-unit/issues/6.

**Comment by slavafomin** [comment]
Fixed in the upstream library: https://github.com/ethjs/ethjs-unit/pull/7.

**Comment by tolya-yanot** [comment]
@mcnckc thanks for the report! This is a bug in the ethjs-unit that tonweb is using. Fixed in tonweb 0.0.41.

Since using Numbers in a crypto is basically a bad practice, in version 0.0.41, in addition to fixing the ethjs-unit, we forbade passing Numbers as an argument at all.

Please pass numbers as strings or BN objects.

This breaks backwards compatibility a bit, but I think it's a good idea to allow developers to avoid precision bugs.

**Comment by EmelyanenkoK** [comment]
@mcnckc please contact @ton_bugs_bot to get bounty reward

**Comment by Afz85** [comment]
Afz185

**Comment by Afz85** [comment]
Afzaalmaher330@gmail.com
